version: 2

jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull Docker image
          command: docker pull ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest
      - run:
          name: Build Docker image
          command: docker build -t ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest --cache-from ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest.
      - run:
          name: Save image
          command: docker image save ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest > ./docker-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./docker-image.tar
          
  push:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load image from tar
          command: docker load -i ./docker-image.tar
      - run:
          name: Login to Docker Hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Push Docker image
          command: docker push ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only:
                - master
